config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers:{
    registrations: 'registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'agencias#index', as: 'home'
  resources:agencias do 
            resources:viajens
  end                   
  
  #Essa linha de codigo define previamente todas as rotas dentro do site 
  #Sendo assim o usuario necessita somente indicar no controller o redirecionamento desejado
  get 'listaAgencias' => 'agencias#listaAgencias' , as: 'listaagencias'
  
  get 'create' => 'agencias#new', as: 'neew' #Agencias#new se refere ao metodo que esta dentro da minhas controller de agencias
  match 'ViajenCreate' => 'viajens#ccre' , via: 'get' 

end


#match 'inicio' => 'restaurantes#index', via: 'get'
#Nesse exemplo o método match recebeu um hash onde a primeira chave é 'inicio' (rota a ser mapeada)
# e o valor para essa chave é 'restaurantes#index', ou seja, quando acessar localhost:3000/inicio
# o Rails vai executar a action index no controller restaurantes.

app/models/agencia.rb
class Agencia < ApplicationRecord
    has_many :viajens 
    validates :nome, presence: true, 
                     length: {minimum: 3}
     
end

app/models/agencium.rb
class Agencium < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/viajen.rb
class Viajen < ApplicationRecord
  belongs_to :agencia
end

app/controllers/agencias_controller.rb
class AgenciasController < ApplicationController
    http_basic_authenticate_with name: "admin", password:"admin", except: [:index, :show]   
    
    def index
        @agencias = Agencia.all
    end
    def listaAgencias
        @agencias = Agencia.all
    end

    def show 
        @agencia = Agencia.find(params[:id])
    end
    def new
        @agencia = Agencia.new
    end
    def create
        #@render plain: params[:agencia].inspect
        @agencia = Agencia.new(agencia_params) 
        if(@agencia.save)
            redirect_to listaagencias_path listaAgencias
        else 
            render 'new'
        end
    end

    def edit 
        puts params
        @agencia = Agencia.find(params[:id])
    end

    def update
        @agencia = Agencia.find(params[:id])
        if(@agencia.update(agencia_params))
            redirect_to listaagencias_path
        else
            render 'edit'
        end
    end
    
    def destroy  
        @agencia = Agencia.find(params[:id])
        @agencia.destroy
        redirect_to listaagencias_path
    end

        

    private def agencia_params
        params.require(:agencia).permit(:nome)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/locais_controller.rb
class LocaisController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private 
    def sign_up_params
        params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end 

    def account_update_params
        params.require(:user).permit(:name,:email,:password,:password_confirmation,:current_password)
    end 

end

app/controllers/viajens_controller.rb
class ViajensController < ApplicationController
    def create
        @agencia = Agencia.find(params[:agencia_id])
        @viajen = @agencia.viajens.create(viajen_params)
        redirect_to agencia_viajens_path

    end
    def index
        redirect_to home_ptha
    end

    def destroy

    end
    private def viajen_params
        params.require(:viajen).permit(:modo,:duracao,:preco,:bagagemMax,:local) 
    end
end

app/helpers/agencias_helper.rb
module AgenciasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locais_helper.rb
module LocaisHelper
end

app/helpers/viajens_helper.rb
module ViajensHelper
end

app/views/agencias/index.html.erb
<h1>Index</h1>

<h3> Os links acima irao redirecionar o usuario para paginas diferentes (:' </h3>


<h5> Escolha uma parte de preferencia e maos na massa :D  </h5>
<h5> Viajens: Lista todas as viajens disponiveis  </h5>
<h5>Companhias: Mostra todas as companhias que o site se vincula </h5>
<h5> Fotos: Mostra a foto dos lugares  </h5>
<h5> A descricao do que cada pagina esta fazendo pode ser encontrada no detalhes das notas em: </h5>
<h5> https://trello.com/b/3LRn2rrT/site-de-viajens </h5>

app/views/agencias/listaAgencias.html.erb
<h2> Lista de agências <h2>
<% @agencias.each do |agencia| %>
    <h3> <%= agencia.nome %> </h3>
    <%= link_to "More", agencia_path(agencia), :class => 'btn btn-default' %>

<% end %>

app/views/agencias/new.erb
<h1> Adicionar agencia </h1>
<%= form_for :agencia, url: agencias_path do |f| %>
    <p>
        <%= f.label :nome %><br> 
        <%= f.text_field(:nome,{:class => 'form-control'})%>
    </p>
    
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<%end%>
    

app/views/agencias/show.html.erb
<h2> Lista de agencias</h2>
<h2><%= @agencia.nome  %> </h2> 
<%= link_to "Delete", agencia_path(@agencia),
                    method: :delete,
                    data: {confirm: 'Are you sure?'},
                    :class => 'btn btn-danger' %>


<hr> 

<h3>Adicionar Viajens</h3>
<%= form_for @agencia.Adicionar do |f| %>
    
    <p>
        <%= f.label :modo %><br> 
        <%= f.text_field(:modo,{:class => 'form-control'})%>
    </p>
    
    <p>
        <%= f.label :duracao %><br> 
        <%= f.text_field(:duracao,{:class => 'form-control'})%>
    </p>
    <p>
        <%= f.label :preco %><br> 
        <%= f.text_field(:preco,{:class => 'form-control'})%>
    </p>
    <p>
        <%= f.label :bagagemMax %><br> 
        <%= f.text_field(:bagagemMax,{:class => 'form-control'})%>
    </p>
    <p>
        <%= f.label :local %><br> 
        <%= f.text_field(:local,{:class => 'form-control'})%>
    </p>
    
    <p>

        <%= f   .submit({:class => 'btn btn-primary'}) %>   
    </p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <title>Viajar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Viajar.com</a>
    </div>
    <ul class="nav navbar-nav">
    <li><%= link_to "Home", home_path %></li>
    <li><a href="#">Viajens</a></li> 
    <li><a href="#">Fotos</a></li>
    <li><a href="#">Sobre Locais</a></li>
    
    <li><%= link_to "Agencias", listaagencias_path %></li>

    <li><a class="dropdown-toggle" data-toggle="dropdown" href="#">Mais
    <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="#">Adicionar viajem</a></li>
      <li><%= link_to "Autorizar nova companhia", neew_path %></li>

    </ul>
  </li>

  </ul>
  <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
    </ul>
    <ul class="nav navbar-nav navbar-right">

  </ul>
  </div>
</nav>
<div class="container">
    <%= yield %>
  </body>
</html>